# Generated by Django 4.1.3 on 2022-11-15 20:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0006_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='joinform',
            old_name='ownername',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='joinform',
            old_name='housenumber',
            new_name='number',
        ),
    ]
