# Generated by Django 4.1.3 on 2022-11-15 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0007_rename_ownername_joinform_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='joinform',
            name='active',
        ),
        migrations.RemoveField(
            model_name='joinform',
            name='date',
        ),
        migrations.AlterField(
            model_name='joinform',
            name='number',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='joinform',
            name='phone',
            field=models.CharField(max_length=50),
        ),
    ]
