# Generated by Django 4.1.3 on 2022-11-16 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0014_alter_joinform_name_alter_joinform_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='joinform',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='joinform',
            name='number',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
        migrations.AlterField(
            model_name='joinform',
            name='phone',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
