# Generated by Django 4.1.3 on 2022-11-15 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0009_alter_joinform_name_alter_joinform_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='joinform',
            name='name',
            field=models.CharField(max_length=200),
        ),
    ]
