# Generated by Django 4.1.3 on 2022-11-15 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0011_alter_joinform_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='joinform',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='joinform',
            name='phone',
            field=models.CharField(max_length=50),
        ),
    ]
