# Generated by Django 4.1.3 on 2022-11-16 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0013_alter_joinform_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='joinform',
            name='name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='joinform',
            name='number',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='joinform',
            name='phone',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
